Added support for SQLite.
marcominerva/DatabaseGPT pull request #61
Opened 2024-02-10 16:19 UTC by nanny07

Fix #25

2024-02-12 08:48 UTC, marcominerva requested changes

2024-02-12 11:19 UTC, nanny07 commented on src/DatabaseGpt.Sqlite/DatabaseGpt.Sqlite.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.1" />
You are right, I wasn't paying attention but the only package needed is "Microsoft.Data.Sqlite"

2024-02-12 11:22 UTC, nanny07 commented on src/DatabaseGpt.Sqlite/SqliteDatabaseGptProvider.cs
> +            SELECT TBL_NAME AS Tables
SQLite doesn't support SCHEMA on the table name like other databases so I've removed that part. [Rerefence](https://www.sqlite.org/lang_naming.html)

How can we handle this?

2024-02-12 11:31 UTC, nanny07 commented on src/DatabaseGpt.Sqlite/SqliteDatabaseGptProvider.cs
> +                WHERE NAME NOT IN (@excludedColumns);
Aren't this enought?
"WHERE NAME NOT IN (@excludedColumns)" 

![image](https://github.com/marcominerva/DatabaseGPT/assets/17173586/e14b9c89-2cb2-43d3-8973-6877fb76e08a)

![image](https://github.com/marcominerva/DatabaseGPT/assets/17173586/513be71e-243f-4b6a-a87c-2ebe54f3e481)

2024-02-12 11:32 UTC, marcominerva commented on src/DatabaseGpt.Sqlite/SqliteDatabaseGptProvider.cs
> +                WHERE NAME NOT IN (@excludedColumns);
Even if you don't have to deal with Schema, there still the need to handle the 'Table.ColumnToExclude' case.

2024-02-13 08:40 UTC, marcominerva approved these changes

2024-02-13 08:49 UTC, merged